In [4]:
import numpy as np
import time
import sys

In [2]:
np.__version__

'1.15.4'

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [18]:
l = list(range(1000))

In [19]:
sys.getsizeof(5)*len(l)

28000

In [10]:
array = np.arange(1000)

In [13]:
array.size*array.itemsize

8000

# List Vs Array

In [38]:
#list
size = 1000000
l1 = list(range(size))
l2 = list(range(size))

In [39]:
start = time.time()
list_result = [(x+y) for x, y in zip(l1, l2)]
print('python list took', (time.time() - start)*1000, 'and size is', sys.getsizeof(1)*len(list_result))

python list took 97.26119041442871 and size is 28000000


In [45]:
#array
a1 = np.arange(size)
a2 = np.arange(size)
start = time.time()
array_result = a1 + a2
print('numpy array took', (time.time() - start)*1000, 'and size is', array_result.size*array_result.itemsize)

numpy array took 3.8633346557617188 and size is 8000000


In [48]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [50]:
a1-a2

array([-3, -3, -3])

In [51]:
a1*a2

array([ 4, 10, 18])

In [52]:
a1/a2

array([0.25, 0.4 , 0.5 ])

In [54]:
a = np.array([[1,2],
            [3,4],
            [5,6]])

In [55]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [56]:
a.ndim

2

In [63]:
a.itemsize

8

In [64]:
a.dtype

dtype('int64')

In [65]:
a = np.array([[1,2],
            [3,4],
            [5,6]], dtype=np.float64)

In [66]:
a.dtype

dtype('float64')

In [67]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [68]:
a.size

6

In [69]:
a.itemsize

8

In [70]:
a.shape

(3, 2)

In [71]:
a = np.array([[1,2],
            [3,4],
            [5,6]], dtype=complex)

In [72]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [73]:
a.size

6

In [74]:
a.dtype

dtype('complex128')

In [75]:
a.itemsize

16

In [77]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [78]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [79]:
np.arange(2,6)

array([2, 3, 4, 5])

In [80]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [81]:
np.arange(2,10,2, np.float64)

array([2., 4., 6., 8.])

In [82]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [83]:
np.linspace(1,5,20, endpoint=True)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [85]:
a = np.array([[1,2],
            [3,4],
            [5,6]])

In [86]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [87]:
a.shape

(3, 2)

In [88]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [90]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [92]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [93]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [95]:
a.min()

1

In [96]:
a.max()

6

In [97]:
a.sum()

21

In [98]:
a.sum(axis=0)

array([ 9, 12])

In [99]:
a.sum(axis=1)

array([ 3,  7, 11])

In [101]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [102]:
np.std(a)

1.707825127659933

In [104]:
a =  np.array([[1,2],
              [3,4]])

In [105]:
b = np.array([[5,6],
             [7,8]])

In [106]:
a,b

(array([[1, 2],
        [3, 4]]), array([[5, 6],
        [7, 8]]))

In [107]:
a+b

array([[ 6,  8],
       [10, 12]])

In [108]:
a-b

array([[-4, -4],
       [-4, -4]])

In [109]:
a*b

array([[ 5, 12],
       [21, 32]])

In [110]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [111]:
a%b

array([[1, 2],
       [3, 4]])

In [114]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [115]:
a**b

array([[    1,    64],
       [ 2187, 65536]])

In [116]:
a = np.array([6,7,8])

In [119]:
a[0:2]

array([6, 7])

In [120]:
b = np.array([[6,7,8], [1,2,4],[9,3,2]])

In [121]:
b

array([[6, 7, 8],
       [1, 2, 4],
       [9, 3, 2]])

In [122]:
b[1,2]

4

In [126]:
b[0:2, 0:2]

array([[6, 7],
       [1, 2]])

In [127]:
b[-1]

array([9, 3, 2])

In [128]:
b[-1,-1]

2

In [133]:
b[:,1:3]

array([[7, 8],
       [2, 4],
       [3, 2]])

In [134]:
for row in b: 
    print(row)

[6 7 8]
[1 2 4]
[9 3 2]


In [149]:
for i in b:
    print(i.dtype)
    for j in i:
        print(j, end=", ")
        print(j.dtype)
    print('\n')

int64
6, int64
7, int64
8, int64


int64
1, int64
2, int64
4, int64


int64
9, int64
3, int64
2, int64




In [159]:
print(*b.flat, sep='\n')

6
7
8
1
2
4
9
3
2


In [169]:
a = np.arange(10).reshape(5,2)
b = np.arange(10,20).reshape(5,2)

In [170]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [171]:
b

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [173]:
np.vstack([a,b])

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [174]:
np.hstack((a,b))

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13],
       [ 4,  5, 14, 15],
       [ 6,  7, 16, 17],
       [ 8,  9, 18, 19]])

In [180]:
c = np.arange(20,25).reshape(1,5)

In [182]:
c

array([[20, 21, 22, 23, 24]])

In [181]:
np.vstack((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [184]:
a = np.arange(30).reshape(2,15)

In [185]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [191]:
result = np.hsplit(a,3)

In [196]:
print(*[[i, row] for i, row in enumerate(result)],sep='\n')

[0, array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])]
[1, array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])]
[2, array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]


In [197]:
result = np.vsplit(a,2)

In [198]:
print(*[[i, row] for i, row in enumerate(result)],sep='\n')

[0, array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])]
[1, array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]


In [199]:
a = np.arange(12).reshape(3,4)

In [200]:
b = a > 2

In [201]:
b

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [202]:
a == 4

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

In [204]:
b = a % 2 == 0

In [205]:
a[b]

array([ 0,  2,  4,  6,  8, 10])

In [207]:
a[b] = -1

In [208]:
a

array([[-1,  1, -1,  3],
       [-1,  5, -1,  7],
       [-1,  9, -1, 11]])

In [209]:
a = np.arange(12).reshape(3,4)

In [210]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [211]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [212]:
for x in np.nditer(a):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [214]:
for x in np.nditer(a, order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [215]:
for x in np.nditer(a, order='A'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [216]:
for x in np.nditer(a, order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [220]:
for x in np.nditer(a, order='K'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [223]:
for x in np.nditer(a, order = 'F', flags = ['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [224]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x*x

In [225]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [227]:
b = np.arange(3,15, 4).reshape(3,1)

In [228]:
b

array([[ 3],
       [ 7],
       [11]])

In [230]:
for x, y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
